// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVlafyZcki9L5NtxLMfSxDTeLuD5Ssn5w',
    appId: '1:406634426394:web:244a731b7e8a5c43b9a1a3',
    messagingSenderId: '406634426394',
    projectId: 'testfirebase-a1943',
    authDomain: 'testfirebase-a1943.firebaseapp.com',
    storageBucket: 'testfirebase-a1943.appspot.com',
    measurementId: 'G-KJMMFCKK13',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHtTEyS9M2kP0RINNs5JCOoBREFJ5YN-k',
    appId: '1:406634426394:android:698dd3715cbcda46b9a1a3',
    messagingSenderId: '406634426394',
    projectId: 'testfirebase-a1943',
    storageBucket: 'testfirebase-a1943.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm86PQc8bra2sTsf0YdysTyYeVWEtLzbQ',
    appId: '1:406634426394:ios:b89de24d25b39614b9a1a3',
    messagingSenderId: '406634426394',
    projectId: 'testfirebase-a1943',
    storageBucket: 'testfirebase-a1943.appspot.com',
    iosBundleId: 'com.example.belajarStateManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm86PQc8bra2sTsf0YdysTyYeVWEtLzbQ',
    appId: '1:406634426394:ios:b89de24d25b39614b9a1a3',
    messagingSenderId: '406634426394',
    projectId: 'testfirebase-a1943',
    storageBucket: 'testfirebase-a1943.appspot.com',
    iosBundleId: 'com.example.belajarStateManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVlafyZcki9L5NtxLMfSxDTeLuD5Ssn5w',
    appId: '1:406634426394:web:94c46a7bbf1722d7b9a1a3',
    messagingSenderId: '406634426394',
    projectId: 'testfirebase-a1943',
    authDomain: 'testfirebase-a1943.firebaseapp.com',
    storageBucket: 'testfirebase-a1943.appspot.com',
    measurementId: 'G-W2EMQVEVRP',
  );
}
